# Generated by Django 5.0.1 on 2024-02-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_adi', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('resim', models.ImageField(upload_to='img/')),
                ('video', models.FileField(upload_to='video/')),
                ('anasayfa_goster', models.BooleanField(default=False)),
                ('kategori', models.ManyToManyField(to='filmApp.kategori')),
            ],
        ),
    ]
