# Generated by Django 5.0.1 on 2024-02-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='resim',
            field=models.ImageField(upload_to='film-img/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(upload_to='film-video/'),
        ),
    ]
