# Generated by Django 5.0.1 on 2024-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0003_kategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
