# Generated by Django 5.0.1 on 2024-02-05 16:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0004_film_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, unique=True),
        ),
    ]
