# Generated by Django 5.0.1 on 2024-02-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0007_film_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='kategori',
        ),
        migrations.AddField(
            model_name='film',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filmApp.kategori'),
        ),
    ]
