# Generated by Django 5.0.1 on 2024-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmApp', '0008_remove_film_kategori_film_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='kategori',
        ),
        migrations.AddField(
            model_name='film',
            name='kategori',
            field=models.ManyToManyField(to='filmApp.kategori'),
        ),
    ]
